# The number of pods that can be lost at once that is still recoverable
# Due to the quorum requirements, this corresponds to 2n+1 of total pods, for example
# the default resiliency of 1 will result in 3 total pods, the resiliency of 2 will result in 5 pods, etc.
# Resiliency of 0 unsurprisingly deploys just a single pod.
resiliency: 1

image:
  repository: typesense/typesense
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nodeResolver:
  image:
    repository: seerun/tsns
    pullPolicy: IfNotPresent
    # Defaults to latest
    tag: ""
  securityContext: {}

storage:
  storageClassName: ""
  size: 10Gi


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  # Note that if this is set to false, it is left up to the user to bind
  # sufficient permissions to monitor kubernetes endpoints to the service account
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8108

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

# Note that if `resilience` >=1 and no other pod affinity is selected, the
# default hard pod antiAffinity is added, preventing from scheduling pods on the
# same nodes.
# If any settings are passed, those overwrite any defaults
affinity: {}