apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense-cluster.fullname" . }}-resolver
  labels:
    {{- include "typesense-cluster.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "typesense-cluster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense-cluster.fullname" . }}
  labels:
    {{- include "typesense-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "typesense-cluster.selectorLabels" . | nindent 4 }}